export type {NavLink} from './navbar.ts'
export type {AppInfo} from './app.ts'
export type {AboutContent, Statistic} from './about.ts'
export type {HeroActions} from './hero.ts'
export type {SkillContent, SkillType, Skill} from './skill.ts'